### ISSUE TITLE
Crash happens on android 8.0

### ISSUE THREAD

**Issue by mr-dunqiu** [AtteqCom/android-log4j2-support#2]
I have implement this project in my app. when i run app on andriod 8.0, crash happens. log is as follows:

08-20 17:38:22.367 22955 23042 E AndroidRuntime: FATAL EXCEPTION: LogUploadThread
08-20 17:38:22.367 22955 23042 E AndroidRuntime: Process: com.qiyi.qaliveshow, PID: 22955
08-20 17:38:22.367 22955 23042 E AndroidRuntime: java.lang.NoClassDefFoundError: org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.util.ReflectionUtil.instantiate(ReflectionUtil.java:185)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:65)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:346)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:161)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:361)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:169)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at com.atteq.log4j.initialization.android.AndroidContextSelector.start(AndroidContextSelector.java:36)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at com.atteq.log4j.initialization.android.AndroidContextSelector.getContext(AndroidContextSelector.java:41)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:142)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:426)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at com.qiyi.qaliveshow.LogUploadService$LogUploadThread.run(LogUploadService.java:160)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.lookup.JmxRuntimeInputArgumentsLookup.<clinit>(JmxRuntimeInputArgumentsLookup.java:35)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.util.LoaderUtil.newInstanceOf(LoaderUtil.java:138)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.util.LoaderUtil.newCheckedInstanceOf(LoaderUtil.java:163)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.util.Loader.newCheckedInstanceOf(Loader.java:311)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:103)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:104)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:30)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:61)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at com.atteq.log4j.initialization.android.AndroidContextSelector.<clinit>(AndroidContextSelector.java:21)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at com.atteq.log4j.initialization.android.AndroidLog4jHelper.initialise(AndroidLog4jHelper.java:40)
08-20 17:38:22.367 22955 23042 E AndroidRuntime: 	at com.qiyi.qaliveshow.LogUploadService$LogUploadThread.run(LogUploadService.java:159)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/base.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_resources_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 	... 13 more
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.qiyi.qaliveshow-3Mz0gTuIczR4Ge3k8n7kHg==/split_lib_resources_apk.apk
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:353)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:100)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:74)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:157)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:716)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:749)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.LoadedApk.getResources(LoadedApk.java:996)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.ContextImpl.createAppContext(ContextImpl.java:2489)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6398)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.ActivityThread.-wrap2(Unknown Source:0)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.os.Handler.dispatchMessage(Handler.java:108)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.os.Looper.loop(Looper.java:166)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at android.app.ActivityThread.main(ActivityThread.java:7425)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at java.lang.reflect.Method.invoke(Native Method)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
08-20 17:38:22.368 22955 23042 E AndroidRuntime: 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
08-20 17:38:22.371   644  1778 W ActivityManager:   Force finishing activity com.qiyi.qaliveshow/.MainActivity

**Comment by ghost** [comment]
Same here!
